from math import *
import time
import wmi
import matplotlib.pyplot as plt

plt.style.use("ggplot")
func = input("Enter function with variable as x: ")

a = float(input("Enter lower limit: "))
b = float(input("Enter upper limit: "))
time_taken = []
heat_generated = []
acc_lst = []
acc = 1
acc_lst.append(acc)
while acc <= 100000:
    start = time.time()
    add = []
    h = (b - a) / (acc * 6)
    table = [0 for i in range(acc * 6 + 1)]
    j = 0
    x = a + j / (float(acc) * 6.0)

    table[0] = eval(func)

    while j < acc * 6:
        j += 1
        x = a + j / (float(acc) * 6.0)
        table[j] = eval(func)

    for i in range(1, len(table) - 1):
        if i % 2 == 0 and i % 3 != 0:
            add.append(table[i])

        if i % 2 != 0 and i % 3 != 0:
            add.append(5*table[i])

        elif i % 6 == 0:
            add.append(2*table[i])

        elif i % 3 == 0 and i % 2 != 0:
            add.append(6*table[i])
    Integration = 0.3 * h * (sum(add) + table[0] + table[-1])

    end = time.time()
    time_taken.append(end-start)

    w = wmi.WMI(namespace="root\\OpenHardwareMonitor")
    temperature_info = w.Sensor()
    for sensor in temperature_info:
        if sensor.SensorType == u'Temperature':
            heat_generated.append(sensor.Value)

    acc *= 10
    acc_lst.append(acc)


plt.scatter(time_taken, heat_generated, marker="o")
plt.xlabel("Time Taken (in seconds)")
plt.ylabel("Heat Generated by CPU (in Celsius)")
plt.title("Time taken -vs- Heat generated")
for (xi, yi, acci) in zip(time_taken, heat_generated, acc_lst):
    plt.text(xi, yi, acci, va="bottom", ha="center")
plt.savefig("1_pross.png")
plt.show()
