import matplotlib.pyplot as plt

plt.style.use("ggplot")

# 1 pross
time_1 = [ 1.4050, 1.2378, 1.2451, 1.1552, 1.2056, 1.2302, 1.2252, 1.3852, 1.6079, 1.4538, 1.6618 ]

heat_1 = [ 72.85416667, 70.35416667, 70.77083333, 71.0625, 69.77083333, 69.47916667, 69.29166667, 70.72916667, 61.5625, 71.9375, 73.625 ]

# ------------------ scatter plot of mean
plt.scatter(time_1, heat_1, label="Single processor", color="#053B50")


# t_indices = acc
# plt.bar(t_indices, heat_1, width=0.3, color="#576CBC")
# plt.xticks(ticks=t_indices, labels=acc)
# plt.xlabel("Number of processors")
# plt.ylabel("Heat Generated by CPU (in Celsius)")
# for (xi, yi, tt) in zip(t_indices, heat_1, time_1):
#     plt.text(xi, yi, str(tt)+" s", ha="center")
#
# plt.show()

# # 2 pross
time_2 = [0.7656960487365723, 0.7458443641662598, 0.7844564914703369, 0.9741408824920654, 1.1739006042480469, 3.9787251949310303]
heat_2 = [69.0, 69.25, 69.375, 70.0, 71.0, 75.625]

plt.scatter(time_2, heat_2, label="2 Processors", color="#952323")


# # 3 pross
time_3 = [0.7646262645721436, 0.8948514461517334, 0.877122163772583, 0.8251965045928955, 1.124906301498413, 2.940133810043335]
heat_3 = [65.5, 67.125, 69.5, 71.0, 72.75, 76.25]

plt.scatter(time_3, heat_3, label="3 Processors", color="#FFBB5C")



# # 4 pross
time_4 = [0.855543851852417, 0.8820643424987793, 0.9468929767608643, 0.9339635372161865, 1.0524771213531494, 2.799865484237671]
heat_4 = [68.125, 69.0, 70.0, 71.0, 71.125, 75.375]

plt.scatter(time_4, heat_4, label="4 Processors", color="#45FFCA")



# # 5 pross
time_5 = [1.0199594497680664, 1.0223362445831299, 0.8272416591644287, 0.8343064785003662, 1.0057921409606934, 2.221590757369995]
heat_5 = [67.625, 68.25, 69.375, 70.625, 72.25, 78.25]

plt.scatter(time_5, heat_5, label="5 Processors", color="#D2DE32")



# # 6 pross
time_6 = [1.0266931056976318, 0.9896090030670166, 0.9497568607330322, 0.9959878921508789, 1.10209059715271, 2.169552803039551]
heat_6 = [62.5, 68.625, 69.625, 70.0, 71.0, 76.875]

plt.scatter(time_6, heat_6, label="6 Processors", color="#FFDBAA")


# # # 7 pross
time_7 = [1.021320104598999, 1.02895188331604, 1.0117301940917969, 1.0095429420471191, 1.1579878330230713, 2.1515214443206787]
heat_7 = [64.5, 66.375, 68.0, 69.625, 72.125, 76.25]

plt.scatter(time_7, heat_7, label="7 Processors", color="#7091F5")



# # # 8 pross
time_8 = [1.152730941772461, 1.0897362232208252, 1.0427260398864746, 1.0075452327728271, 1.1157827377319336, 1.9424381256103516]
heat_8 = [62.875, 65.625, 68.125, 71.125, 71.625, 76.375]

plt.scatter(time_8, heat_8, label="8 Processors", color="#A8DF8E")



# # # 9 pross
time_9 = [1.1673943996429443, 1.1735563278198242, 1.1143467426300049, 1.1282002925872803, 1.319976806640625, 2.4080464839935303]
heat_9 = [64.625, 66.375, 71.5, 72.375, 72.75, 76.75]

plt.scatter(time_9, heat_9, label="9 Processors", color="#279EFF")



# # # 10 pross
time_10 = [1.7266719341278076, 1.464982271194458, 1.4320528507232666, 1.5040631294250488, 1.3947665691375732, 2.1246566772460938]
heat_10 = [57.5, 57.875, 59.25, 60.125, 60.75, 73.875]

plt.scatter(time_10, heat_10, label="10 Processors", color="#5C4B99")


# #
# # # 11 pross
time_11 = [1.309244155883789, 1.2861874103546143, 1.2667055130004883, 1.2506554126739502, 1.4409503936767578, 2.1691160202026367]
heat_11 = [61.375, 69.875, 70.5, 74.375, 74.0, 81.5]

plt.scatter(time_11, heat_11, label="11 Processors", color="#C70039")



# # # 12 pross
time_12 = [1.735769271850586, 1.4266357421875, 1.485079288482666, 1.4548492431640625, 1.521590232849121, 2.34698224067688]
heat_12 = [68.125, 69.875, 73.125, 73.125, 75.375, 82.125]

plt.scatter(time_12, heat_12, label="12 Processors", color="#65451F")


plt.xlabel("Time Taken")
plt.ylabel("Heat Generated")
plt.title("Time Taken -vs- Heat Generated Graph\nFor multiple processors")
plt.legend()
# plt.savefig("mean_pross_bar.png")
plt.show()
